DEFAULTS: &DEFAULTS
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *DEFAULTS
  database: development_<%= ENV["DATABASE_NAME"] %>

test:
  <<: *DEFAULTS
  database: test_<%= ENV["DATABASE_NAME"] %>

production:
  <<: *DEFAULTS
  database: production_<%= ENV["DATABASE_NAME"] %>
  